### ISSUE TITLE
Update data tab with new layout to download data

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_site#19]
I'm thinking on a grid with two rows: `Accessibility` and `Land use` data
The accessibility row would have two columns: `public transport/car` and `active` data.
The landuse row would have two columns as well: `demographic` and `land use` data.
Instead of having one file for each year or one big file with all the years, maybe we can add a little checkbox where the use can select one or multiple years and download the data accordingly.  I think this would require a plumber API to either filter or bind the data (other option would be to create all the combinations of years and uploading to our servers - not ideal). Maybe an overkill, but I think it would be nice :)

**Comment by kauebraga** [comment]
Sketch

![image](https://user-images.githubusercontent.com/22420248/182363816-7fbe2904-e0db-4499-8478-2eaf9e41d9ae.png)

**Comment by kauebraga** [comment]
(honestly, I think we should just stick with the current table layout rs)

**Comment by rafapereirabr** [comment]
I quite like the current layout. It is very simple because it makes users download all data sets in a single file. This approach comes with a few  problems, though.

1. The accessibility data set for cars is not avaiable for all years. I believe the current layout should make this clear.
2. Also, the current layout does not separate sociodemographic data from land use data. This is a problem because they come from different years of reference. On top of that, we would like to generate new sociodemographic data set with updated info onde the 2022 census is published.

I would suggest we use the something like the layout below. But perhaps we should also have a separate panel for the land use data. The problem is, what we do with the geometry data. Should the geometry data be embarked with the population data? or with the access and land use data? or should it be a separate panel.

<img width="381" alt="Untitled" src="https://user-images.githubusercontent.com/7448421/182485272-ed87c44f-c437-4618-8355-88d67d0cb62c.png">
